# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-14 02:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mainshop'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mainshop',
            table='axf_mainshow',
        ),
    ]
