# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-01-16 01:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='axf_cart',
        ),
    ]
